package dns

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"strings"
	"time"

	"hproxy/config"
)

// SmartDNS 实现 DNSProvider 接口
type SmartDNS struct {
	ConfFile     string // 主配置文件路径
	OutputFile   string // 生成的域名配置文件路径
	ReloadCmd    string // 重载命令（为空则跳过重载）
	lastDomains  map[string]string // 上次写入的域名→IP 映射
	lastUpdateTime time.Time // 上次更新时间（用于判断文件是否被外部修改）
}

// NewSmartDNS 创建 SmartDNS 实例
func NewSmartDNS(config map[string]interface{}) (*SmartDNS, error) {
	s := &SmartDNS{
		lastDomains: make(map[string]string),
	}
	if v, ok := config["conf_file"]; ok {
		s.ConfFile = v.(string)
	}
	if v, ok := config["output_file"]; ok {
		s.OutputFile = v.(string)
	}
	if v, ok := config["reload_cmd"]; ok {
		s.ReloadCmd = v.(string)
	}
	return s, nil
}

func (s *SmartDNS) Name() string {
	return "smartdns"
}

// UpdateDomains 更新域名配置（带变更检测）
func (s *SmartDNS) UpdateDomains(domains map[string]string) error {
	needUpdate := false

	// 1. 检查域名集合是否有变化
	if !s.compareDomains(domains) {
		config.DebugLog("[SmartDNS] 域名有变化")
		needUpdate = true
	}

	// 2. 检查 OutputFile 是否被外部修改
	if s.isFileModified(s.OutputFile, s.lastUpdateTime) {
		config.DebugLog("[SmartDNS] 域名配置文件被外部修改")
		needUpdate = true
	}

	// 3. 检查 ConfFile 是否被外部修改
	if s.ConfFile != "" && s.isFileModified(s.ConfFile, s.lastUpdateTime) {
		config.DebugLog("[SmartDNS] 主配置文件被外部修改")
		needUpdate = true
	}

	if !needUpdate {
		config.DebugLog("[SmartDNS] 无变化，跳过更新")
		return nil
	}

	// 4. 生成配置内容
	entries := make([]DomainEntry, 0, len(domains))
	seen := make(map[string]bool)

	for domain, ip := range domains {
		if strings.HasPrefix(domain, "*") {
			standard := normalizeWildcard(domain)
			if standard != "" && !seen[standard] {
				entries = append(entries, DomainEntry{Domain: standard, IP: ip})
				seen[standard] = true
			}
		} else {
			if !seen[domain] {
				entries = append(entries, DomainEntry{Domain: domain, IP: ip})
				seen[domain] = true
			}
		}
	}

	header := fmt.Sprintf("# Auto-generated by hproxy @ %s\n# Total: %d domains\n# Last update: %s\n",
		time.Now().Format("2006-01-02 15:04:05"),
		len(entries),
		time.Now().Format("2006-01-02 15:04:05"))

	format := "address /{domain}/{ip}"
	content := GenerateConfig(entries, format, header)

	// 5. 写文件
	if err := os.WriteFile(s.OutputFile, []byte(content), 0644); err != nil {
		log.Printf("[SmartDNS] 写文件失败 %s: %v", s.OutputFile, err)
		return err
	}

	// 确保数据刷盘后，再读文件时间
	f, err := os.Open(s.OutputFile)
	if err == nil {
		f.Sync()
		f.Close()
	}

	// 6. 更新状态（读文件的真实修改时间）
	s.lastDomains = make(map[string]string)
	for k, v := range domains {
		s.lastDomains[k] = v
	}
	s.updateLastUpdateTime()
	log.Printf("[SmartDNS] 已更新 %d 条域名到 %s", len(domains), s.OutputFile)

	// 7. 确保主配置引用了生成文件
	return s.ensureConfig()
}

// compareDomains 比较域名集合是否有变化
func (s *SmartDNS) compareDomains(domains map[string]string) bool {
	if len(domains) != len(s.lastDomains) {
		return false
	}
	for domain, ip := range domains {
		lastIP, ok := s.lastDomains[domain]
		if !ok || lastIP != ip {
			return false
		}
	}
	return true
}

// isFileModified 检查文件是否被外部修改（修改时间 > lastUpdateTime）
func (s *SmartDNS) isFileModified(filePath string, lastUpdateTime time.Time) bool {
	info, err := os.Stat(filePath)
	if err != nil {
		return true // 文件不存在，认为被修改
	}
	// 文件修改时间晚于上次更新时间，认为被外部修改
	// 差 5 秒都不是问题（说明文件被外部改了）
	return info.ModTime().After(lastUpdateTime)
}

// updateLastUpdateTime 更新最后更新时间（取当前所有相关文件的最新修改时间）
func (s *SmartDNS) updateLastUpdateTime() {
	latest := time.Now()

	// 检查 OutputFile 的修改时间
	if info, err := os.Stat(s.OutputFile); err == nil {
		if info.ModTime().After(latest) {
			latest = info.ModTime()
		}
	}

	// 检查 ConfFile 的修改时间
	if s.ConfFile != "" {
		if info, err := os.Stat(s.ConfFile); err == nil {
			if info.ModTime().After(latest) {
				latest = info.ModTime()
			}
		}
	}

	s.lastUpdateTime = latest
}

func (s *SmartDNS) ensureConfig() error {
	if s.ConfFile == "" {
		return nil
	}
	data, err := os.ReadFile(s.ConfFile)
	if err != nil {
		log.Printf("[SmartDNS] 读取主配置失败 %s: %v", s.ConfFile, err)
		return err
	}
	content := string(data)
	if strings.Contains(content, s.OutputFile) {
		return nil
	}
	f, err := os.OpenFile(s.ConfFile, os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		log.Printf("[SmartDNS] 打开主配置失败 %s: %v", s.ConfFile, err)
		return err
	}
	defer f.Close()
	_, err = f.WriteString("\nconf-file " + s.OutputFile + "\n")
	if err != nil {
		log.Printf("[SmartDNS] 写入主配置失败 %s: %v", s.ConfFile, err)
		return err
	}
	f.Sync()

	// 更新最后更新时间
	s.updateLastUpdateTime()
	config.DebugLog("[SmartDNS] 已更新主配置文件")
	return nil
}

func (s *SmartDNS) Reload() error {
	if s.ReloadCmd == "" {
		config.DebugLog("[SmartDNS] 未配置 reload_cmd，跳过重载")
		return nil
	}
	cmd := exec.Command("sh", "-c", s.ReloadCmd)
	if err := cmd.Run(); err != nil {
		config.DebugLog("[SmartDNS] 重载失败（smartdns 可能未运行）: %v", err)
	}
	config.DebugLog("[SmartDNS] 已重载")
	return nil
}

// normalizeWildcard 把通配符转成标准格式
func normalizeWildcard(wildcard string) string {
	suffix := strings.TrimPrefix(wildcard, "*")
	if strings.HasPrefix(suffix, ".") {
		return suffix
	}
	idx := strings.Index(suffix, ".")
	if idx == -1 {
		return ""
	}
	return suffix[idx:]
}
